name: Release new action version
on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
defaults:
  run:
    shell: pwsh

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  update_tag:
    permissions:
      id-token: write
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    # Remember to configure the releaseNewActionVersion environment with required approvers in the repository settings
    environment:
      name: releaseNewActionVersion
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518
      with:
        allowed-endpoints: 
          api.github.com:443
          github.com:443
          prod.api.stepsecurity.io:443

    - uses: step-security/wait-for-secrets@main
      id: wait-for-secrets
      with:
        secrets: |
          PAT: 
            name: PAT to create tag
            description: Generate new PAT and delete after release
    - name: Update the ${{ env.TAG_NAME }} tag
      uses: step-security/publish-action@b438f840875fdcb7d1de4fc3d1d30e86cf6acb5d
      with:
        source-tag: ${{ env.TAG_NAME }}
        token: ${{ steps.wait-for-secrets.outputs.PAT }}
